services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    container_name: call-assist-dev
    volumes:
      - ..:/workspaces/universal:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ../runtime/claude-state:/home/vscode/.claude
    command: sleep infinity
    environment:
      - DOCKER_HOST=unix:///var/run/docker-host.sock

  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: call-assist-ha
    volumes:
      - ./integration:/config/custom_components/call_assist
      - ../runtime/ha_config:/config
    ports:
      - "8123:8123"
    environment:
      - TZ=UTC
    restart: unless-stopped

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: call-assist-synapse
    volumes:
      - ../runtime/synapse_data:/data
      - ./config/synapse/homeserver.yaml:/data/homeserver.yaml
    ports:
      - "8008:8008"
      - "8448:8448"
    environment:
      - SYNAPSE_SERVER_NAME=localhost
      - SYNAPSE_REPORT_STATS=no
      - UID=0
      - GID=0
    depends_on:
      - coturn
    restart: unless-stopped

  coturn:
    image: coturn/coturn:latest
    container_name: call-assist-coturn
    volumes:
      - ./config/coturn/turnserver.conf:/etc/coturn/turnserver.conf
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/udp"
      - "5349:5349/tcp"
      - "49152-49252:49152-49252/udp"
    command: ["-c", "/etc/coturn/turnserver.conf"]
    restart: unless-stopped

