"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ConfigurationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class CameraEntitiesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class MediaPlayerEntitiesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    CAMERA_ENTITIES_FIELD_NUMBER: builtins.int
    MEDIA_PLAYER_ENTITIES_FIELD_NUMBER: builtins.int
    ENABLED_PROTOCOLS_FIELD_NUMBER: builtins.int
    @property
    def camera_entities(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """entity_id -> friendly_name"""

    @property
    def media_player_entities(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """entity_id -> friendly_name"""

    @property
    def enabled_protocols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """["matrix", "xmpp"]"""

    def __init__(
        self,
        *,
        camera_entities: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        media_player_entities: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        enabled_protocols: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["camera_entities", b"camera_entities", "enabled_protocols", b"enabled_protocols", "media_player_entities", b"media_player_entities"]) -> None: ...

global___ConfigurationRequest = ConfigurationRequest

@typing.final
class ConfigurationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___ConfigurationResponse = ConfigurationResponse

@typing.final
class CredentialsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class CredentialsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    PROTOCOL_FIELD_NUMBER: builtins.int
    CREDENTIALS_FIELD_NUMBER: builtins.int
    protocol: builtins.str
    """"matrix" or "xmpp" """
    @property
    def credentials(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """username, password, server, etc."""

    def __init__(
        self,
        *,
        protocol: builtins.str = ...,
        credentials: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["credentials", b"credentials", "protocol", b"protocol"]) -> None: ...

global___CredentialsRequest = CredentialsRequest

@typing.final
class CredentialsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___CredentialsResponse = CredentialsResponse

@typing.final
class CallRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CAMERA_ENTITY_ID_FIELD_NUMBER: builtins.int
    MEDIA_PLAYER_ENTITY_ID_FIELD_NUMBER: builtins.int
    TARGET_ADDRESS_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    PREFERRED_CAPABILITIES_FIELD_NUMBER: builtins.int
    camera_entity_id: builtins.str
    media_player_entity_id: builtins.str
    target_address: builtins.str
    """Matrix room ID or XMPP JID"""
    protocol: builtins.str
    """"matrix" or "xmpp" """
    @property
    def preferred_capabilities(self) -> common_pb2.MediaCapabilities: ...
    def __init__(
        self,
        *,
        camera_entity_id: builtins.str = ...,
        media_player_entity_id: builtins.str = ...,
        target_address: builtins.str = ...,
        protocol: builtins.str = ...,
        preferred_capabilities: common_pb2.MediaCapabilities | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["preferred_capabilities", b"preferred_capabilities"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["camera_entity_id", b"camera_entity_id", "media_player_entity_id", b"media_player_entity_id", "preferred_capabilities", b"preferred_capabilities", "protocol", b"protocol", "target_address", b"target_address"]) -> None: ...

global___CallRequest = CallRequest

@typing.final
class CallResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    CALL_ID_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    INITIAL_STATE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    call_id: builtins.str
    message: builtins.str
    initial_state: common_pb2.CallState.ValueType
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        call_id: builtins.str = ...,
        message: builtins.str = ...,
        initial_state: common_pb2.CallState.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["call_id", b"call_id", "initial_state", b"initial_state", "message", b"message", "success", b"success"]) -> None: ...

global___CallResponse = CallResponse

@typing.final
class CallTerminateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: builtins.int
    call_id: builtins.str
    def __init__(
        self,
        *,
        call_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["call_id", b"call_id"]) -> None: ...

global___CallTerminateRequest = CallTerminateRequest

@typing.final
class CallTerminateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___CallTerminateResponse = CallTerminateResponse

@typing.final
class SystemCapabilities(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BROKER_CAPABILITIES_FIELD_NUMBER: builtins.int
    AVAILABLE_PLUGINS_FIELD_NUMBER: builtins.int
    @property
    def broker_capabilities(self) -> common_pb2.MediaCapabilities: ...
    @property
    def available_plugins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PluginCapabilities]: ...
    def __init__(
        self,
        *,
        broker_capabilities: common_pb2.MediaCapabilities | None = ...,
        available_plugins: collections.abc.Iterable[global___PluginCapabilities] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["broker_capabilities", b"broker_capabilities"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["available_plugins", b"available_plugins", "broker_capabilities", b"broker_capabilities"]) -> None: ...

global___SystemCapabilities = SystemCapabilities

@typing.final
class PluginCapabilities(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROTOCOL_FIELD_NUMBER: builtins.int
    AVAILABLE_FIELD_NUMBER: builtins.int
    CAPABILITIES_FIELD_NUMBER: builtins.int
    protocol: builtins.str
    available: builtins.bool
    @property
    def capabilities(self) -> common_pb2.MediaCapabilities: ...
    def __init__(
        self,
        *,
        protocol: builtins.str = ...,
        available: builtins.bool = ...,
        capabilities: common_pb2.MediaCapabilities | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["capabilities", b"capabilities"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["available", b"available", "capabilities", b"capabilities", "protocol", b"protocol"]) -> None: ...

global___PluginCapabilities = PluginCapabilities
