"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PluginConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class CredentialsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class SettingsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    PROTOCOL_FIELD_NUMBER: builtins.int
    CREDENTIALS_FIELD_NUMBER: builtins.int
    SETTINGS_FIELD_NUMBER: builtins.int
    protocol: builtins.str
    """"matrix" or "xmpp" """
    @property
    def credentials(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def settings(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Additional protocol-specific settings"""

    def __init__(
        self,
        *,
        protocol: builtins.str = ...,
        credentials: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        settings: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["credentials", b"credentials", "protocol", b"protocol", "settings", b"settings"]) -> None: ...

global___PluginConfig = PluginConfig

@typing.final
class PluginStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INITIALIZED_FIELD_NUMBER: builtins.int
    AUTHENTICATED_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    CAPABILITIES_FIELD_NUMBER: builtins.int
    initialized: builtins.bool
    authenticated: builtins.bool
    message: builtins.str
    @property
    def capabilities(self) -> common_pb2.MediaCapabilities: ...
    def __init__(
        self,
        *,
        initialized: builtins.bool = ...,
        authenticated: builtins.bool = ...,
        message: builtins.str = ...,
        capabilities: common_pb2.MediaCapabilities | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["capabilities", b"capabilities"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authenticated", b"authenticated", "capabilities", b"capabilities", "initialized", b"initialized", "message", b"message"]) -> None: ...

global___PluginStatus = PluginStatus

@typing.final
class CallStartRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: builtins.int
    TARGET_ADDRESS_FIELD_NUMBER: builtins.int
    CAMERA_STREAM_URL_FIELD_NUMBER: builtins.int
    CAMERA_CAPABILITIES_FIELD_NUMBER: builtins.int
    PLAYER_CAPABILITIES_FIELD_NUMBER: builtins.int
    call_id: builtins.str
    target_address: builtins.str
    camera_stream_url: builtins.str
    @property
    def camera_capabilities(self) -> common_pb2.MediaCapabilities: ...
    @property
    def player_capabilities(self) -> common_pb2.MediaCapabilities: ...
    def __init__(
        self,
        *,
        call_id: builtins.str = ...,
        target_address: builtins.str = ...,
        camera_stream_url: builtins.str = ...,
        camera_capabilities: common_pb2.MediaCapabilities | None = ...,
        player_capabilities: common_pb2.MediaCapabilities | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["camera_capabilities", b"camera_capabilities", "player_capabilities", b"player_capabilities"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["call_id", b"call_id", "camera_capabilities", b"camera_capabilities", "camera_stream_url", b"camera_stream_url", "player_capabilities", b"player_capabilities", "target_address", b"target_address"]) -> None: ...

global___CallStartRequest = CallStartRequest

@typing.final
class CallStartResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    REMOTE_STREAM_URL_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    state: common_pb2.CallState.ValueType
    remote_stream_url: builtins.str
    """URL for incoming video stream"""
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
        state: common_pb2.CallState.ValueType = ...,
        remote_stream_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "remote_stream_url", b"remote_stream_url", "state", b"state", "success", b"success"]) -> None: ...

global___CallStartResponse = CallStartResponse

@typing.final
class CallAcceptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: builtins.int
    CAMERA_STREAM_URL_FIELD_NUMBER: builtins.int
    CAPABILITIES_FIELD_NUMBER: builtins.int
    call_id: builtins.str
    camera_stream_url: builtins.str
    @property
    def capabilities(self) -> common_pb2.MediaCapabilities: ...
    def __init__(
        self,
        *,
        call_id: builtins.str = ...,
        camera_stream_url: builtins.str = ...,
        capabilities: common_pb2.MediaCapabilities | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["capabilities", b"capabilities"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["call_id", b"call_id", "camera_stream_url", b"camera_stream_url", "capabilities", b"capabilities"]) -> None: ...

global___CallAcceptRequest = CallAcceptRequest

@typing.final
class CallAcceptResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    REMOTE_STREAM_URL_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    remote_stream_url: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
        remote_stream_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "remote_stream_url", b"remote_stream_url", "success", b"success"]) -> None: ...

global___CallAcceptResponse = CallAcceptResponse

@typing.final
class CallEndRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    call_id: builtins.str
    reason: builtins.str
    def __init__(
        self,
        *,
        call_id: builtins.str = ...,
        reason: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["call_id", b"call_id", "reason", b"reason"]) -> None: ...

global___CallEndRequest = CallEndRequest

@typing.final
class CallEndResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___CallEndResponse = CallEndResponse

@typing.final
class MediaNegotiationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: builtins.int
    LOCAL_CAPABILITIES_FIELD_NUMBER: builtins.int
    REMOTE_CAPABILITIES_FIELD_NUMBER: builtins.int
    call_id: builtins.str
    @property
    def local_capabilities(self) -> common_pb2.MediaCapabilities: ...
    @property
    def remote_capabilities(self) -> common_pb2.MediaCapabilities: ...
    def __init__(
        self,
        *,
        call_id: builtins.str = ...,
        local_capabilities: common_pb2.MediaCapabilities | None = ...,
        remote_capabilities: common_pb2.MediaCapabilities | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["local_capabilities", b"local_capabilities", "remote_capabilities", b"remote_capabilities"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["call_id", b"call_id", "local_capabilities", b"local_capabilities", "remote_capabilities", b"remote_capabilities"]) -> None: ...

global___MediaNegotiationRequest = MediaNegotiationRequest
