"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _CallState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CallStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CallState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CALL_STATE_UNKNOWN: _CallState.ValueType  # 0
    CALL_STATE_INITIATING: _CallState.ValueType  # 1
    CALL_STATE_RINGING: _CallState.ValueType  # 2
    CALL_STATE_CONNECTING: _CallState.ValueType  # 3
    CALL_STATE_ACTIVE: _CallState.ValueType  # 4
    CALL_STATE_ENDING: _CallState.ValueType  # 5
    CALL_STATE_ENDED: _CallState.ValueType  # 6
    CALL_STATE_FAILED: _CallState.ValueType  # 7

class CallState(_CallState, metaclass=_CallStateEnumTypeWrapper): ...

CALL_STATE_UNKNOWN: CallState.ValueType  # 0
CALL_STATE_INITIATING: CallState.ValueType  # 1
CALL_STATE_RINGING: CallState.ValueType  # 2
CALL_STATE_CONNECTING: CallState.ValueType  # 3
CALL_STATE_ACTIVE: CallState.ValueType  # 4
CALL_STATE_ENDING: CallState.ValueType  # 5
CALL_STATE_ENDED: CallState.ValueType  # 6
CALL_STATE_FAILED: CallState.ValueType  # 7
global___CallState = CallState

class _CallEventType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CallEventTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CallEventType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CALL_EVENT_UNKNOWN: _CallEventType.ValueType  # 0
    CALL_EVENT_INITIATED: _CallEventType.ValueType  # 1
    CALL_EVENT_RINGING: _CallEventType.ValueType  # 2
    CALL_EVENT_ANSWERED: _CallEventType.ValueType  # 3
    CALL_EVENT_MEDIA_READY: _CallEventType.ValueType  # 4
    CALL_EVENT_ENDED: _CallEventType.ValueType  # 5
    CALL_EVENT_ERROR: _CallEventType.ValueType  # 6

class CallEventType(_CallEventType, metaclass=_CallEventTypeEnumTypeWrapper): ...

CALL_EVENT_UNKNOWN: CallEventType.ValueType  # 0
CALL_EVENT_INITIATED: CallEventType.ValueType  # 1
CALL_EVENT_RINGING: CallEventType.ValueType  # 2
CALL_EVENT_ANSWERED: CallEventType.ValueType  # 3
CALL_EVENT_MEDIA_READY: CallEventType.ValueType  # 4
CALL_EVENT_ENDED: CallEventType.ValueType  # 5
CALL_EVENT_ERROR: CallEventType.ValueType  # 6
global___CallEventType = CallEventType

@typing.final
class Resolution(google.protobuf.message.Message):
    """Common types used across services"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    FRAMERATE_FIELD_NUMBER: builtins.int
    width: builtins.int
    height: builtins.int
    framerate: builtins.int
    def __init__(
        self,
        *,
        width: builtins.int = ...,
        height: builtins.int = ...,
        framerate: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["framerate", b"framerate", "height", b"height", "width", b"width"]) -> None: ...

global___Resolution = Resolution

@typing.final
class MediaCapabilities(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIDEO_CODECS_FIELD_NUMBER: builtins.int
    AUDIO_CODECS_FIELD_NUMBER: builtins.int
    SUPPORTED_RESOLUTIONS_FIELD_NUMBER: builtins.int
    HARDWARE_ACCELERATION_FIELD_NUMBER: builtins.int
    WEBRTC_SUPPORT_FIELD_NUMBER: builtins.int
    MAX_BANDWIDTH_KBPS_FIELD_NUMBER: builtins.int
    hardware_acceleration: builtins.bool
    webrtc_support: builtins.bool
    max_bandwidth_kbps: builtins.int
    @property
    def video_codecs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def audio_codecs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def supported_resolutions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Resolution]: ...
    def __init__(
        self,
        *,
        video_codecs: collections.abc.Iterable[builtins.str] | None = ...,
        audio_codecs: collections.abc.Iterable[builtins.str] | None = ...,
        supported_resolutions: collections.abc.Iterable[global___Resolution] | None = ...,
        hardware_acceleration: builtins.bool = ...,
        webrtc_support: builtins.bool = ...,
        max_bandwidth_kbps: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["audio_codecs", b"audio_codecs", "hardware_acceleration", b"hardware_acceleration", "max_bandwidth_kbps", b"max_bandwidth_kbps", "supported_resolutions", b"supported_resolutions", "video_codecs", b"video_codecs", "webrtc_support", b"webrtc_support"]) -> None: ...

global___MediaCapabilities = MediaCapabilities

@typing.final
class MediaNegotiation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SELECTED_VIDEO_CODEC_FIELD_NUMBER: builtins.int
    SELECTED_AUDIO_CODEC_FIELD_NUMBER: builtins.int
    SELECTED_RESOLUTION_FIELD_NUMBER: builtins.int
    DIRECT_STREAMING_FIELD_NUMBER: builtins.int
    TRANSCODING_REQUIRED_FIELD_NUMBER: builtins.int
    STREAM_URL_FIELD_NUMBER: builtins.int
    selected_video_codec: builtins.str
    selected_audio_codec: builtins.str
    direct_streaming: builtins.bool
    transcoding_required: builtins.bool
    stream_url: builtins.str
    @property
    def selected_resolution(self) -> global___Resolution: ...
    def __init__(
        self,
        *,
        selected_video_codec: builtins.str = ...,
        selected_audio_codec: builtins.str = ...,
        selected_resolution: global___Resolution | None = ...,
        direct_streaming: builtins.bool = ...,
        transcoding_required: builtins.bool = ...,
        stream_url: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["selected_resolution", b"selected_resolution"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["direct_streaming", b"direct_streaming", "selected_audio_codec", b"selected_audio_codec", "selected_resolution", b"selected_resolution", "selected_video_codec", b"selected_video_codec", "stream_url", b"stream_url", "transcoding_required", b"transcoding_required"]) -> None: ...

global___MediaNegotiation = MediaNegotiation

@typing.final
class CallEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    CALL_ID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    type: global___CallEventType.ValueType
    call_id: builtins.str
    state: global___CallState.ValueType
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        type: global___CallEventType.ValueType = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        call_id: builtins.str = ...,
        state: global___CallState.ValueType = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["call_id", b"call_id", "metadata", b"metadata", "state", b"state", "timestamp", b"timestamp", "type", b"type"]) -> None: ...

global___CallEvent = CallEvent

@typing.final
class HealthStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEALTHY_FIELD_NUMBER: builtins.int
    COMPONENT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    healthy: builtins.bool
    component: builtins.str
    message: builtins.str
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        healthy: builtins.bool = ...,
        component: builtins.str = ...,
        message: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["component", b"component", "healthy", b"healthy", "message", b"message", "timestamp", b"timestamp"]) -> None: ...

global___HealthStatus = HealthStatus
